[versions]
android-gradle-plugin = '8.13.2'
android-material = '1.13.0'
androidx-appcompat = '1.7.1'
androidx-core-ktx = '1.17.0'
androidx-fragment-ktx = '1.8.9'
androidx-lifecycle-viewmodel-ktx = '2.10.0'
androidx-sqlite = '2.6.2'
google-flexbox = '3.0.0'
kotlin-android = '2.3.0'
sqlcipher = '4.12.0'

[plugins]
android-application = { id = 'com.android.application', version.ref = 'android-gradle-plugin' }
kotlin-android = { id = 'org.jetbrains.kotlin.android', version.ref = 'kotlin-android' }

[libraries]
android-material = { module = 'com.google.android.material:material', version.ref = 'android-material' }
androidx-appcompat = { module = 'androidx.appcompat:appcompat', version.ref = 'androidx-appcompat' }
androidx-core-ktx = { module = 'androidx.core:core-ktx', version.ref = 'androidx-core-ktx' }
androidx-fragment-ktx = { module = 'androidx.fragment:fragment-ktx', version.ref = 'androidx-fragment-ktx' }
androidx-lifecycle-viewmodel-ktx = { group = 'androidx.lifecycle', name = 'lifecycle-viewmodel-ktx', version.ref = 'androidx-lifecycle-viewmodel-ktx' }
androidx-sqlite = { group = 'androidx.sqlite', name = 'sqlite', version.ref = 'androidx-sqlite' }
google-flexbox = { group = 'com.google.android.flexbox', name = 'flexbox', version.ref = 'google-flexbox'}
sqlcipher = { group = 'net.zetetic', name = 'sqlcipher-android', version.ref = 'sqlcipher' }
